version: '3.4'

services:
  db:
    container_name: db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DATABASE}
    volumes:
      - 'jg_data:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: exit 0

  app:
    container_name: jasongallagher
    volumes:
      - './public:/src/public'
    ports:
      - '3100:3100'
    env_file: ./.env
    restart: always
    depends_on:
      - db

  staging:
    container_name: jasongallagher-staging
    image: jasongallagher:staging
    volumes:
      - './public:/src/public'
    ports:
      - '3200:3200'
    env_file: ./.env.staging
    restart: always
    depends_on:
      - db

networks:
  default:
    external:
      name: jg
volumes:
  jg_data: