version: '3.4'

services:
  db-staging:
    # image: jasongallagher_db:staging
    image: registry.gitlab.com/unleashit/jasongallagher.org/db_staging

  db-production:
    container_name: jasongallagher_db-prod
    # image: jasongallagher_db:prod
    image: registry.gitlab.com/unleashit/jasongallagher.org/db_prod
    ports:
      - '5433:5432'
    env_file:
      - ./secrets/.env.database-init.prod
    volumes:
      - 'jg_data:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: exit 0

  app-production:
    container_name: jasongallagher_app-prod
    # image: jasongallagher_app:prod
    image: registry.gitlab.com/unleashit/jasongallagher.org/app_prod
    ports:
      - '3100:3100'
    volumes:
      - './public:/src/public'
    env_file: ./secrets/.env
    restart: 'always'
    depends_on:
      - db-production
    environment:
    - NODE_ENV=production

  app-staging:
    container_name: jasongallagher_app-staging
    # image: jasongallagher_app:staging
    image: registry.gitlab.com/unleashit/jasongallagher.org/app_staging
    ports:
      - '3200:3200'
    volumes:
      - './public:/src/public'
    env_file: ./secrets/.env.staging
    restart: 'always'
    depends_on:
      - db-staging
    environment:
      - NODE_ENV=production

volumes:
  jg_data:
  jg_data_staging:
